#!/usr/bin/env ansible-playbook

- name: Run DHCP server
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: deploy dhcpd
      import_role:
        name: ../../ansible-role-dhcpd-docker

